### ISSUE TITLE
Small thing

### ISSUE THREAD

**Issue by williamvongphan** [aymanhabib/softdev#1]
HW 09 is supposed to be in the 09_flask-static directory in the root of the repository, not under 08_serve. Just want to make sure your work can be seen by Mr. Mykolyk's automated tools.

**Comment by aymanhabib** [comment]
tysm for telling me 🙏🏽🙌🏽

**Comment by thunder-red-star** [comment]
Closes #1

**Comment by thunder-red-star** [comment]
wrong acc
